[package]
name = "nix-debug-adapter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "1.26.0"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
snafu = "0.7.4"
nll = { git = "https://github.com/EspressoSystems/nll" }

[profile.release]
incremental = true
