[package]
name = "nix-debug-adapter"
license = "MIT"
version = "0.1.0"
edition = "2021"
description = "Nix Debug Adapter Implementation (DAP)"

[dependencies]
tokio = "1.26.0"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
snafu = "0.7.4"

[profile.release]
incremental = true
