[workspace]
resolver = "2"
members = [
        "nix-bindings",
        "nix-debug-adapter",
        "dap-server",
]

[profile.release]
incremental = true
panic = "abort"

[profile.dev]
panic = "abort"
