name: "Build and push to cachix"

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  builds:
    name: Test tree-sitter grammar
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0 # Nix Flakes doesn't work on shallow clones
    - uses: cachix/install-nix-action@v18
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
    - uses: cachix/cachix-action@v12
      with:
        name: jrestivo
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: |
        nix develop -c "just"
